server:
  port: 8002
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30

# spring
spring:
  datasource:
    url: jdbc:mysql://rdsb2emir2yjjry.mysql.rds.aliyuncs.com:3306/store?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ENC(FRkJG3JyNu7/K0XsNHcr9Q==)
    password: ENC(wmdVNs2rTK914M5NJXfpt8/sYrcdoAUL)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

  redis:
    host: 10.81.245.32
    database: 1
    port: 6379
    timeout: 3000ms

  rabbitmq:
    addresses: 10.81.245.32
    username: guest
    password: ENC(PRpwXXJMcX+sAqWS0oKFEQ==)

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

  servlet:
    multipart:
      max-file-size: 5Mb
      max-request-size: 5Mb

# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.d2c.store.modules.*.model
  global-config:
    db-config:
      id-type: id_worker
      field-strategy: not_null
      logic-delete-value: 1
      logic-not-delete-value: 0
    sql-parser-cache: false
  configuration:
    auto-mapping-behavior: partial
    map-underscore-to-camel-case: true
    cache-enabled: false
#   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# ignored-urls
ignored:
  urls:
    - /api/**
    - /download/**
    - /login/expired
    - /swagger-ui.html
    - /swagger-resources/**
    - /webjars/**
    - /v2/api-docs

# store-sdk
store:
  sms:
    dahantc:
      account: ENC(UX8bZOr3oWSvBczS+9SsRA==)
      password: ENC(4uCdGxmEQtkdF+Pgl+GVkIE1xpUn36f0)
    emay:
      app-id: ENC(XQog7PISRxUqqMbp13596SRyjFgN1jPA9Xeptahdv4E=)
      secret-key: ENC(SWDJ+0cXQrvtMRn/6UbXHYg8WFEsI2Fsm37V54Ogo2U=)
  fadada:
    host: https://extapi.fadada.com/api2/
    app-id: ENC(6dUxaZKQAaKtoXZZY6Z14A==)
    app-secret: ENC(XdqqJ8XT8eoSGJnjRZM6SnzMCVZAt/C+Fs68vdw6NmBovl8bt7iSKw==)
    notify-url: https://yliao.com/api/callback/fadada
    template-id: TEMPLATE_KS_1
  p2p:
    ks:
      notice-url: https://www.kesudai.com.cn/gt/notifyUserOrder/d2c
      secret-key: ENC(jRptIRUrL0q14dLCgtG8ZfXOBet/5TJmpPKP+uiTDvjOk91Y9nyvAXQPyqBfSqUd)

#logging:
#  level:
#    root: debug